### ISSUE TITLE
The fudge cone isn't animating properly

### ISSUE THREAD

**Issue by juliannastepha** [juliannastepha/frozen-not-in-time#1]
@charlie-quinn
My Markbot keeps popping up this message. The animation is working correctly in the browser, but for some reason Markbot doesn't think it's working right. I just can't figure out why.
<img width="999" alt="Screen Shot 2019-10-14 at 11 10 59 AM" src="https://user-images.githubusercontent.com/43150245/66762100-51a61780-ee73-11e9-8732-228f04fd5d73.png">

**Comment by charlie-quinn** [comment]
🤖Markbot may not be happy because the animation doesn't quite match the example. I can also spot a number of other issues:
- [ ] animation is slower than the example (needs to be sped up)
- [ ] the cherry should appear _after_ the text on the left
- [ ] the text on the left should have a blur filter + animate on an angle
- [ ] the background gradient's colours are incorrect

Since some of these points can be a little tricky to understand, let's go over them together in class this week. 🤓

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
